# Generated by Django 5.2.1 on 2026-06-30 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZalaryConfigMirror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.CharField(max_length=1024, unique=True)),
                ('platform_admin_party', models.CharField(db_index=True, max_length=512)),
                ('supported_tokens', models.JSONField(blank=True, default=list)),
                ('default_token', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('ledger_offset', models.CharField(blank=True, max_length=255)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyMirror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.CharField(max_length=1024, unique=True)),
                ('company_id', models.CharField(db_index=True, max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('platform_admin_party', models.CharField(db_index=True, max_length=512)),
                ('company_admin_party', models.CharField(db_index=True, max_length=512)),
                ('admin_wallet_parties', models.JSONField(blank=True, default=list)),
                ('hr_wallet_parties', models.JSONField(blank=True, default=list)),
                ('employer_wallet_parties', models.JSONField(blank=True, default=list)),
                ('allowed_tokens', models.JSONField(blank=True, default=list)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('ledger_offset', models.CharField(blank=True, max_length=255)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['company_id', 'company_admin_party'], name='zalary_comp_company_737e9b_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeEnrollmentMirror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.CharField(max_length=1024, unique=True)),
                ('company_id', models.CharField(db_index=True, max_length=255)),
                ('company_admin_party', models.CharField(db_index=True, max_length=512)),
                ('hr_wallet_party', models.CharField(db_index=True, max_length=512)),
                ('employer_wallet_party', models.CharField(db_index=True, max_length=512)),
                ('employee_wallet_party', models.CharField(db_index=True, max_length=512)),
                ('employee_external_id', models.CharField(db_index=True, max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('ledger_offset', models.CharField(blank=True, max_length=255)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['company_id', 'employee_external_id'], name='zalary_empl_company_0442ca_idx')],
            },
        ),
        migrations.CreateModel(
            name='LedgerCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_id', models.CharField(max_length=255, unique=True)),
                ('workflow_id', models.CharField(blank=True, max_length=255)),
                ('act_as', models.JSONField(blank=True, default=list)),
                ('read_as', models.JSONField(blank=True, default=list)),
                ('template_id', models.CharField(blank=True, max_length=512)),
                ('contract_id', models.CharField(blank=True, max_length=1024)),
                ('choice_name', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('submitted', 'Submitted'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='draft', max_length=32)),
                ('update_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='zalary_ledg_status_a028a8_idx'), models.Index(fields=['template_id', 'choice_name'], name='zalary_ledg_templat_4d450d_idx')],
            },
        ),
        migrations.CreateModel(
            name='LedgerContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.CharField(max_length=1024, unique=True)),
                ('template_id', models.CharField(db_index=True, max_length=512)),
                ('module_name', models.CharField(blank=True, max_length=255)),
                ('entity_name', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('contract_key', models.JSONField(blank=True, null=True)),
                ('signatories', models.JSONField(blank=True, default=list)),
                ('observers', models.JSONField(blank=True, default=list)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_update_id', models.CharField(blank=True, max_length=255)),
                ('archived_update_id', models.CharField(blank=True, max_length=255)),
                ('ledger_offset', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['template_id', 'active'], name='zalary_ledg_templat_847bf7_idx'), models.Index(fields=['ledger_offset'], name='zalary_ledg_ledger__c911e8_idx')],
            },
        ),
        migrations.CreateModel(
            name='LedgerParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_id', models.CharField(max_length=512, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(blank=True, choices=[('platform_admin', 'Platform admin'), ('company_admin', 'Company admin'), ('hr', 'HR'), ('employer', 'Employer'), ('employee', 'Employee')], max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['role', 'is_active'], name='zalary_ledg_role_42a5c8_idx')],
            },
        ),
        migrations.CreateModel(
            name='PayrollVaultMirror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.CharField(max_length=1024, unique=True)),
                ('company_id', models.CharField(db_index=True, max_length=255)),
                ('payroll_id', models.CharField(db_index=True, max_length=255)),
                ('company_admin_party', models.CharField(db_index=True, max_length=512)),
                ('hr_wallet_party', models.CharField(db_index=True, max_length=512)),
                ('employer_wallet_party', models.CharField(db_index=True, max_length=512)),
                ('vault_status', models.CharField(db_index=True, max_length=64)),
                ('payroll_period', models.JSONField(blank=True, default=dict)),
                ('payroll_token', models.JSONField(blank=True, default=dict)),
                ('claim_window_start', models.DateTimeField(blank=True, null=True)),
                ('claim_window_end', models.DateTimeField(blank=True, null=True)),
                ('totals', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('ledger_offset', models.CharField(blank=True, max_length=255)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['company_id', 'payroll_id'], name='zalary_payr_company_6699de_idx'), models.Index(fields=['vault_status', 'claim_window_end'], name='zalary_payr_vault_s_f3c1df_idx')],
            },
        ),
        migrations.CreateModel(
            name='SalaryAllocationMirror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.CharField(max_length=1024, unique=True)),
                ('company_id', models.CharField(db_index=True, max_length=255)),
                ('payroll_id', models.CharField(db_index=True, max_length=255)),
                ('employee_external_id', models.CharField(db_index=True, max_length=255)),
                ('employee_wallet_party', models.CharField(db_index=True, max_length=512)),
                ('employer_wallet_party', models.CharField(db_index=True, max_length=512)),
                ('hr_wallet_party', models.CharField(db_index=True, max_length=512)),
                ('company_admin_party', models.CharField(db_index=True, max_length=512)),
                ('allocation_status', models.CharField(db_index=True, max_length=64)),
                ('salary_breakdown', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('ledger_offset', models.CharField(blank=True, max_length=255)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['company_id', 'payroll_id', 'employee_external_id'], name='zalary_sala_company_a37eb8_idx'), models.Index(fields=['allocation_status'], name='zalary_sala_allocat_7f4d42_idx')],
            },
        ),
        migrations.CreateModel(
            name='SalaryClaimMirror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.CharField(max_length=1024, unique=True)),
                ('company_id', models.CharField(db_index=True, max_length=255)),
                ('payroll_id', models.CharField(db_index=True, max_length=255)),
                ('employee_external_id', models.CharField(db_index=True, max_length=255)),
                ('employee_wallet_party', models.CharField(db_index=True, max_length=512)),
                ('employer_wallet_party', models.CharField(db_index=True, max_length=512)),
                ('hr_wallet_party', models.CharField(db_index=True, max_length=512)),
                ('company_admin_party', models.CharField(db_index=True, max_length=512)),
                ('claim_status', models.CharField(db_index=True, max_length=64)),
                ('claim_amount', models.DecimalField(decimal_places=10, max_digits=36)),
                ('source_allocation_contract_id', models.CharField(max_length=1024)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('ledger_offset', models.CharField(blank=True, max_length=255)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['company_id', 'payroll_id', 'employee_external_id'], name='zalary_sala_company_286a4d_idx'), models.Index(fields=['claim_status'], name='zalary_sala_claim_s_518222_idx')],
            },
        ),
        migrations.CreateModel(
            name='SettlementProofMirror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(db_index=True, max_length=255)),
                ('payroll_id', models.CharField(db_index=True, max_length=255)),
                ('employee_external_id', models.CharField(db_index=True, max_length=255)),
                ('employee_wallet_party', models.CharField(db_index=True, max_length=512)),
                ('employer_wallet_party', models.CharField(db_index=True, max_length=512)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=36)),
                ('settlement_reference', models.CharField(db_index=True, max_length=255)),
                ('proof_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ledger_command', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlement_proofs', to='zalary.ledgercommand')),
            ],
            options={
                'indexes': [models.Index(fields=['company_id', 'payroll_id', 'employee_external_id'], name='zalary_sett_company_ae8cad_idx'), models.Index(fields=['settlement_reference'], name='zalary_sett_settlem_d369ed_idx')],
            },
        ),
    ]
