# Generated by Django 5.2.1 on 2026-06-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zalary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zalaryconfigmirror',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zalaryconfigmirror',
            name='ledger_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='zalaryconfigmirror',
            name='ledger_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zalaryconfigmirror',
            name='package_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='zalaryconfigmirror',
            name='template_id',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddIndex(
            model_name='zalaryconfigmirror',
            index=models.Index(fields=['template_id', 'ledger_active'], name='zalary_zala_templat_d24f6e_idx'),
        ),
        migrations.AddIndex(
            model_name='zalaryconfigmirror',
            index=models.Index(fields=['platform_admin_party', 'is_active'], name='zalary_zala_platfor_308458_idx'),
        ),
    ]
