# Generated by Codex on 2026-06-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zalary", "0002_zalaryconfigmirror_last_seen_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClaimTicketMirror",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("contract_id", models.CharField(max_length=1024, unique=True)),
                ("company_id", models.CharField(db_index=True, max_length=255)),
                ("payroll_id", models.CharField(db_index=True, max_length=255)),
                ("employee_external_id", models.CharField(db_index=True, max_length=255)),
                ("employee_wallet_party", models.CharField(db_index=True, max_length=512)),
                ("employer_wallet_party", models.CharField(db_index=True, max_length=512)),
                ("hr_wallet_party", models.CharField(db_index=True, max_length=512)),
                ("company_admin_party", models.CharField(db_index=True, max_length=512)),
                ("ticket_amount", models.DecimalField(decimal_places=10, max_digits=36)),
                ("ticket_token", models.JSONField(blank=True, default=dict)),
                ("salary_breakdown", models.JSONField(blank=True, default=dict)),
                ("source_allocation_contract_id", models.CharField(max_length=1024)),
                ("claim_window_start", models.DateTimeField(blank=True, null=True)),
                ("claim_window_end", models.DateTimeField(blank=True, null=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("ledger_offset", models.CharField(blank=True, max_length=255)),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name="claimticketmirror",
            index=models.Index(
                fields=["company_id", "payroll_id", "employee_external_id"],
                name="zalary_clai_company_8326fb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="claimticketmirror",
            index=models.Index(fields=["claim_window_end"], name="zalary_clai_claim_w_d75d45_idx"),
        ),
    ]
