# Generated by Django 5.2.1 on 2026-07-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zalary', '0003_claimticketmirror'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedSalaryClaimMirror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.CharField(max_length=1024, unique=True)),
                ('company_id', models.CharField(db_index=True, max_length=255)),
                ('payroll_id', models.CharField(db_index=True, max_length=255)),
                ('employee_external_id', models.CharField(db_index=True, max_length=255)),
                ('employee_wallet_party', models.CharField(db_index=True, max_length=512)),
                ('employer_wallet_party', models.CharField(db_index=True, max_length=512)),
                ('hr_wallet_party', models.CharField(db_index=True, max_length=512)),
                ('company_admin_party', models.CharField(db_index=True, max_length=512)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=36)),
                ('failure_reason', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('ledger_offset', models.CharField(blank=True, max_length=255)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['company_id', 'payroll_id', 'employee_external_id'], name='zalary_fail_company_1f62d8_idx')],
            },
        ),
        migrations.CreateModel(
            name='PayslipMirror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.CharField(max_length=1024, unique=True)),
                ('company_id', models.CharField(db_index=True, max_length=255)),
                ('payroll_id', models.CharField(db_index=True, max_length=255)),
                ('employee_external_id', models.CharField(db_index=True, max_length=255)),
                ('employee_wallet_party', models.CharField(db_index=True, max_length=512)),
                ('employer_wallet_party', models.CharField(db_index=True, max_length=512)),
                ('hr_wallet_party', models.CharField(db_index=True, max_length=512)),
                ('company_admin_party', models.CharField(db_index=True, max_length=512)),
                ('salary_breakdown', models.JSONField(blank=True, default=dict)),
                ('settlement_proof', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('ledger_offset', models.CharField(blank=True, max_length=255)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['company_id', 'payroll_id', 'employee_external_id'], name='zalary_pays_company_26fc63_idx')],
            },
        ),
        migrations.CreateModel(
            name='SettledSalaryRecordMirror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.CharField(max_length=1024, unique=True)),
                ('company_id', models.CharField(db_index=True, max_length=255)),
                ('payroll_id', models.CharField(db_index=True, max_length=255)),
                ('employee_external_id', models.CharField(db_index=True, max_length=255)),
                ('employee_wallet_party', models.CharField(db_index=True, max_length=512)),
                ('employer_wallet_party', models.CharField(db_index=True, max_length=512)),
                ('hr_wallet_party', models.CharField(db_index=True, max_length=512)),
                ('company_admin_party', models.CharField(db_index=True, max_length=512)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=36)),
                ('settlement_reference', models.CharField(db_index=True, max_length=255)),
                ('settlement_proof', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('ledger_offset', models.CharField(blank=True, max_length=255)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['company_id', 'payroll_id', 'employee_external_id'], name='zalary_sett_company_c2c317_idx'), models.Index(fields=['settlement_reference'], name='zalary_sett_settlem_07f01d_idx')],
            },
        ),
        migrations.CreateModel(
            name='SettlementReceiptMirror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.CharField(max_length=1024, unique=True)),
                ('company_id', models.CharField(db_index=True, max_length=255)),
                ('payroll_id', models.CharField(db_index=True, max_length=255)),
                ('employee_external_id', models.CharField(db_index=True, max_length=255)),
                ('employee_wallet_party', models.CharField(db_index=True, max_length=512)),
                ('employer_wallet_party', models.CharField(db_index=True, max_length=512)),
                ('hr_wallet_party', models.CharField(db_index=True, max_length=512)),
                ('company_admin_party', models.CharField(db_index=True, max_length=512)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=36)),
                ('settlement_reference', models.CharField(db_index=True, max_length=255)),
                ('settlement_proof', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('ledger_offset', models.CharField(blank=True, max_length=255)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['company_id', 'payroll_id', 'employee_external_id'], name='zalary_sett_company_8ee252_idx'), models.Index(fields=['settlement_reference'], name='zalary_sett_settlem_4b15d1_idx')],
            },
        ),
    ]
