# Generated by Django 5.2.1 on 2026-07-01 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zalary', '0004_failedsalaryclaimmirror_payslipmirror_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimticketmirror',
            name='ledger_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='salaryclaimmirror',
            name='ledger_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.CreateModel(
            name='USDCxTransferRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(db_index=True, max_length=255)),
                ('payroll_id', models.CharField(db_index=True, max_length=255)),
                ('employee_external_id', models.CharField(db_index=True, max_length=255)),
                ('salary_claim_contract_id', models.CharField(db_index=True, max_length=1024)),
                ('settlement_reference', models.CharField(db_index=True, max_length=255)),
                ('provider_name', models.CharField(blank=True, db_index=True, max_length=128)),
                ('provider_status', models.CharField(db_index=True, max_length=32)),
                ('sender_party', models.CharField(db_index=True, max_length=512)),
                ('receiver_party', models.CharField(db_index=True, max_length=512)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=36)),
                ('token', models.JSONField(blank=True, default=dict)),
                ('transfer_instruction_cid', models.CharField(blank=True, max_length=1024)),
                ('holding_cid', models.CharField(blank=True, max_length=1024)),
                ('raw_provider_reference', models.CharField(blank=True, max_length=1024)),
                ('proof_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ledger_command', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usdcx_transfer_records', to='zalary.ledgercommand')),
            ],
            options={
                'indexes': [models.Index(fields=['company_id', 'payroll_id', 'employee_external_id'], name='zalary_usdc_company_2e2c14_idx'), models.Index(fields=['salary_claim_contract_id', 'settlement_reference'], name='zalary_usdc_salary__3ea0f7_idx'), models.Index(fields=['provider_name', 'provider_status'], name='zalary_usdc_provide_4a3c53_idx')],
            },
        ),
    ]
