# Generated by Django 5.2.1 on 2026-07-01 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zalary', '0005_claimticketmirror_ledger_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZUSDHoldingMirror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.CharField(max_length=1024, unique=True)),
                ('issuer_party', models.CharField(db_index=True, max_length=512)),
                ('owner_party', models.CharField(db_index=True, max_length=512)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=36)),
                ('symbol', models.CharField(db_index=True, default='ZUSD', max_length=16)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('ledger_active', models.BooleanField(db_index=True, default=True)),
                ('ledger_offset', models.CharField(blank=True, max_length=255)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['owner_party', 'symbol', 'ledger_active'], name='zalary_zusd_owner_p_c44c14_idx'), models.Index(fields=['issuer_party', 'reference'], name='zalary_zusd_issuer__c78686_idx')],
            },
        ),
        migrations.CreateModel(
            name='ZUSDFaucetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=255, unique=True)),
                ('owner_party', models.CharField(db_index=True, max_length=512)),
                ('issuer_party', models.CharField(blank=True, db_index=True, max_length=512)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=36)),
                ('symbol', models.CharField(default='ZUSD', max_length=16)),
                ('reference', models.CharField(db_index=True, max_length=255)),
                ('environment', models.CharField(db_index=True, default='sandbox', max_length=64)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('minted', 'Minted'), ('failed', 'Failed'), ('rejected', 'Rejected')], db_index=True, default='requested', max_length=32)),
                ('holding_contract_id', models.CharField(blank=True, max_length=1024)),
                ('grant_contract_id', models.CharField(blank=True, max_length=1024)),
                ('update_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('failure_reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('minted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ledger_command', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zusd_faucet_requests', to='zalary.ledgercommand')),
            ],
            options={
                'indexes': [models.Index(fields=['owner_party', 'environment', 'status', 'created_at'], name='zalary_zusd_owner_p_9d6e03_idx'), models.Index(fields=['reference', 'status'], name='zalary_zusd_referen_ba4b70_idx')],
            },
        ),
    ]
